name: Update summary.md

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run update_summary.py
      run: |
        python .github/workflows/update_summary.py
    
    - name: Commit and push changes if updated
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add summary.md
        git diff --cached --quiet || git commit -m "Auto-update summary.md"
        git push origin main
